// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PaymentDetailsentity4 PaymentDetailsentity4
//
// Payment details
//
// swagger:model PaymentDetailsentity4
type PaymentDetailsentity4 struct {

	// The amount of payment applied to escrow
	EscrowAmount float64 `json:"escrowAmount,omitempty"`

	// The amount of payment applied to fees
	FeesAmount float64 `json:"feesAmount,omitempty"`

	// The amount of payment applied to life/health/accident insurance on the loan
	InsuranceAmount float64 `json:"insuranceAmount,omitempty"`

	// The amount of payment applied to interest
	InterestAmount float64 `json:"interestAmount,omitempty"`

	// The amount of payment applied to PMI
	PmiAmount float64 `json:"pmiAmount,omitempty"`

	// The amount of payment applied to principal
	PrincipalAmount float64 `json:"principalAmount,omitempty"`
}

// Validate validates this payment detailsentity4
func (m *PaymentDetailsentity4) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this payment detailsentity4 based on context it is used
func (m *PaymentDetailsentity4) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PaymentDetailsentity4) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaymentDetailsentity4) UnmarshalBinary(b []byte) error {
	var res PaymentDetailsentity4
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
