// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Number0 Indicates whether the advertised overdraft rate is guaranteed to be offered to a borrower by the bank e.g. if it�s part of a government scheme, or whether the rate may vary dependent on the applicant�s circumstances.
//
// swagger:model Number_0
type Number0 int64

// Validate validates this number 0
func (m Number0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this number 0 based on context it is used
func (m Number0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
