// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// OBSupplementaryData1 Additional information that can not be captured in the structured fields and/or any other specific block.
//
// swagger:model OBSupplementaryData1
type OBSupplementaryData1 interface{}
