// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// LoanPaymentFrequency2 LoanPaymentFrequency2
//
// WEEKLY, BIWEEKLY, TWICEMONTHLY, MONTHLY, FOURWEEKS, BIMONTHLY, QUARTERLY, SEMIANNUALLY, ANNUALLY, OTHER
//
// swagger:model LoanPaymentFrequency2
type LoanPaymentFrequency2 string

func NewLoanPaymentFrequency2(value LoanPaymentFrequency2) *LoanPaymentFrequency2 {
	v := value
	return &v
}

const (

	// LoanPaymentFrequency2ANNUALLY captures enum value "ANNUALLY"
	LoanPaymentFrequency2ANNUALLY LoanPaymentFrequency2 = "ANNUALLY"

	// LoanPaymentFrequency2BIMONTHLY captures enum value "BIMONTHLY"
	LoanPaymentFrequency2BIMONTHLY LoanPaymentFrequency2 = "BIMONTHLY"

	// LoanPaymentFrequency2BIWEEKLY captures enum value "BIWEEKLY"
	LoanPaymentFrequency2BIWEEKLY LoanPaymentFrequency2 = "BIWEEKLY"

	// LoanPaymentFrequency2FOURWEEKS captures enum value "FOURWEEKS"
	LoanPaymentFrequency2FOURWEEKS LoanPaymentFrequency2 = "FOURWEEKS"

	// LoanPaymentFrequency2MONTHLY captures enum value "MONTHLY"
	LoanPaymentFrequency2MONTHLY LoanPaymentFrequency2 = "MONTHLY"

	// LoanPaymentFrequency2OTHER captures enum value "OTHER"
	LoanPaymentFrequency2OTHER LoanPaymentFrequency2 = "OTHER"

	// LoanPaymentFrequency2QUARTERLY captures enum value "QUARTERLY"
	LoanPaymentFrequency2QUARTERLY LoanPaymentFrequency2 = "QUARTERLY"

	// LoanPaymentFrequency2SEMIANNUALLY captures enum value "SEMIANNUALLY"
	LoanPaymentFrequency2SEMIANNUALLY LoanPaymentFrequency2 = "SEMIANNUALLY"

	// LoanPaymentFrequency2TWICEMONTHLY captures enum value "TWICEMONTHLY"
	LoanPaymentFrequency2TWICEMONTHLY LoanPaymentFrequency2 = "TWICEMONTHLY"

	// LoanPaymentFrequency2WEEKLY captures enum value "WEEKLY"
	LoanPaymentFrequency2WEEKLY LoanPaymentFrequency2 = "WEEKLY"
)

// for schema
var loanPaymentFrequency2Enum []interface{}

func init() {
	var res []LoanPaymentFrequency2
	if err := json.Unmarshal([]byte(`["ANNUALLY","BIMONTHLY","BIWEEKLY","FOURWEEKS","MONTHLY","OTHER","QUARTERLY","SEMIANNUALLY","TWICEMONTHLY","WEEKLY"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		loanPaymentFrequency2Enum = append(loanPaymentFrequency2Enum, v)
	}
}

func (m LoanPaymentFrequency2) validateLoanPaymentFrequency2Enum(path, location string, value LoanPaymentFrequency2) error {
	if err := validate.EnumCase(path, location, value, loanPaymentFrequency2Enum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this loan payment frequency2
func (m LoanPaymentFrequency2) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateLoanPaymentFrequency2Enum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this loan payment frequency2 based on context it is used
func (m LoanPaymentFrequency2) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
