// Code generated by go-swagger; DO NOT EDIT.

package payment_details

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/cloudentity/openbanking-quickstart/openbanking/paymentinitiation/models"
)

// GetDomesticPaymentsDomesticPaymentIDPaymentDetailsReader is a Reader for the GetDomesticPaymentsDomesticPaymentIDPaymentDetails structure.
type GetDomesticPaymentsDomesticPaymentIDPaymentDetailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 406:
		result := NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsOK creates a GetDomesticPaymentsDomesticPaymentIDPaymentDetailsOK with default headers values
func NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsOK() *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsOK {
	return &GetDomesticPaymentsDomesticPaymentIDPaymentDetailsOK{}
}

/* GetDomesticPaymentsDomesticPaymentIDPaymentDetailsOK describes a response with status code 200, with default header values.

Payment Details Read
*/
type GetDomesticPaymentsDomesticPaymentIDPaymentDetailsOK struct {

	/* An RFC4122 UID used as a correlation id.
	 */
	XFapiInteractionID string

	/* Header containing a detached JWS signature of the body of the payload.

	 */
	XJwsSignature string

	Payload *models.OBWritePaymentDetailsResponse1
}

func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsOK) Error() string {
	return fmt.Sprintf("[GET /domestic-payments/{DomesticPaymentId}/payment-details][%d] getDomesticPaymentsDomesticPaymentIdPaymentDetailsOK  %+v", 200, o.Payload)
}
func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsOK) GetPayload() *models.OBWritePaymentDetailsResponse1 {
	return o.Payload
}

func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-fapi-interaction-id
	hdrXFapiInteractionID := response.GetHeader("x-fapi-interaction-id")

	if hdrXFapiInteractionID != "" {
		o.XFapiInteractionID = hdrXFapiInteractionID
	}

	// hydrates response header x-jws-signature
	hdrXJwsSignature := response.GetHeader("x-jws-signature")

	if hdrXJwsSignature != "" {
		o.XJwsSignature = hdrXJwsSignature
	}

	o.Payload = new(models.OBWritePaymentDetailsResponse1)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsBadRequest creates a GetDomesticPaymentsDomesticPaymentIDPaymentDetailsBadRequest with default headers values
func NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsBadRequest() *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsBadRequest {
	return &GetDomesticPaymentsDomesticPaymentIDPaymentDetailsBadRequest{}
}

/* GetDomesticPaymentsDomesticPaymentIDPaymentDetailsBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetDomesticPaymentsDomesticPaymentIDPaymentDetailsBadRequest struct {

	/* An RFC4122 UID used as a correlation id.
	 */
	XFapiInteractionID string

	/* Header containing a detached JWS signature of the body of the payload.

	 */
	XJwsSignature string

	Payload *models.OBErrorResponse1
}

func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsBadRequest) Error() string {
	return fmt.Sprintf("[GET /domestic-payments/{DomesticPaymentId}/payment-details][%d] getDomesticPaymentsDomesticPaymentIdPaymentDetailsBadRequest  %+v", 400, o.Payload)
}
func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsBadRequest) GetPayload() *models.OBErrorResponse1 {
	return o.Payload
}

func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-fapi-interaction-id
	hdrXFapiInteractionID := response.GetHeader("x-fapi-interaction-id")

	if hdrXFapiInteractionID != "" {
		o.XFapiInteractionID = hdrXFapiInteractionID
	}

	// hydrates response header x-jws-signature
	hdrXJwsSignature := response.GetHeader("x-jws-signature")

	if hdrXJwsSignature != "" {
		o.XJwsSignature = hdrXJwsSignature
	}

	o.Payload = new(models.OBErrorResponse1)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsUnauthorized creates a GetDomesticPaymentsDomesticPaymentIDPaymentDetailsUnauthorized with default headers values
func NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsUnauthorized() *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsUnauthorized {
	return &GetDomesticPaymentsDomesticPaymentIDPaymentDetailsUnauthorized{}
}

/* GetDomesticPaymentsDomesticPaymentIDPaymentDetailsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetDomesticPaymentsDomesticPaymentIDPaymentDetailsUnauthorized struct {

	/* An RFC4122 UID used as a correlation id.
	 */
	XFapiInteractionID string
}

func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /domestic-payments/{DomesticPaymentId}/payment-details][%d] getDomesticPaymentsDomesticPaymentIdPaymentDetailsUnauthorized ", 401)
}

func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-fapi-interaction-id
	hdrXFapiInteractionID := response.GetHeader("x-fapi-interaction-id")

	if hdrXFapiInteractionID != "" {
		o.XFapiInteractionID = hdrXFapiInteractionID
	}

	return nil
}

// NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsForbidden creates a GetDomesticPaymentsDomesticPaymentIDPaymentDetailsForbidden with default headers values
func NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsForbidden() *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsForbidden {
	return &GetDomesticPaymentsDomesticPaymentIDPaymentDetailsForbidden{}
}

/* GetDomesticPaymentsDomesticPaymentIDPaymentDetailsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetDomesticPaymentsDomesticPaymentIDPaymentDetailsForbidden struct {

	/* An RFC4122 UID used as a correlation id.
	 */
	XFapiInteractionID string

	/* Header containing a detached JWS signature of the body of the payload.

	 */
	XJwsSignature string

	Payload *models.OBErrorResponse1
}

func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsForbidden) Error() string {
	return fmt.Sprintf("[GET /domestic-payments/{DomesticPaymentId}/payment-details][%d] getDomesticPaymentsDomesticPaymentIdPaymentDetailsForbidden  %+v", 403, o.Payload)
}
func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsForbidden) GetPayload() *models.OBErrorResponse1 {
	return o.Payload
}

func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-fapi-interaction-id
	hdrXFapiInteractionID := response.GetHeader("x-fapi-interaction-id")

	if hdrXFapiInteractionID != "" {
		o.XFapiInteractionID = hdrXFapiInteractionID
	}

	// hydrates response header x-jws-signature
	hdrXJwsSignature := response.GetHeader("x-jws-signature")

	if hdrXJwsSignature != "" {
		o.XJwsSignature = hdrXJwsSignature
	}

	o.Payload = new(models.OBErrorResponse1)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotFound creates a GetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotFound with default headers values
func NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotFound() *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotFound {
	return &GetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotFound{}
}

/* GetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotFound describes a response with status code 404, with default header values.

Not found
*/
type GetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotFound struct {

	/* An RFC4122 UID used as a correlation id.
	 */
	XFapiInteractionID string
}

func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotFound) Error() string {
	return fmt.Sprintf("[GET /domestic-payments/{DomesticPaymentId}/payment-details][%d] getDomesticPaymentsDomesticPaymentIdPaymentDetailsNotFound ", 404)
}

func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-fapi-interaction-id
	hdrXFapiInteractionID := response.GetHeader("x-fapi-interaction-id")

	if hdrXFapiInteractionID != "" {
		o.XFapiInteractionID = hdrXFapiInteractionID
	}

	return nil
}

// NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsMethodNotAllowed creates a GetDomesticPaymentsDomesticPaymentIDPaymentDetailsMethodNotAllowed with default headers values
func NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsMethodNotAllowed() *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsMethodNotAllowed {
	return &GetDomesticPaymentsDomesticPaymentIDPaymentDetailsMethodNotAllowed{}
}

/* GetDomesticPaymentsDomesticPaymentIDPaymentDetailsMethodNotAllowed describes a response with status code 405, with default header values.

Method Not Allowed
*/
type GetDomesticPaymentsDomesticPaymentIDPaymentDetailsMethodNotAllowed struct {

	/* An RFC4122 UID used as a correlation id.
	 */
	XFapiInteractionID string
}

func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsMethodNotAllowed) Error() string {
	return fmt.Sprintf("[GET /domestic-payments/{DomesticPaymentId}/payment-details][%d] getDomesticPaymentsDomesticPaymentIdPaymentDetailsMethodNotAllowed ", 405)
}

func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-fapi-interaction-id
	hdrXFapiInteractionID := response.GetHeader("x-fapi-interaction-id")

	if hdrXFapiInteractionID != "" {
		o.XFapiInteractionID = hdrXFapiInteractionID
	}

	return nil
}

// NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotAcceptable creates a GetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotAcceptable with default headers values
func NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotAcceptable() *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotAcceptable {
	return &GetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotAcceptable{}
}

/* GetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotAcceptable describes a response with status code 406, with default header values.

Not Acceptable
*/
type GetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotAcceptable struct {

	/* An RFC4122 UID used as a correlation id.
	 */
	XFapiInteractionID string
}

func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotAcceptable) Error() string {
	return fmt.Sprintf("[GET /domestic-payments/{DomesticPaymentId}/payment-details][%d] getDomesticPaymentsDomesticPaymentIdPaymentDetailsNotAcceptable ", 406)
}

func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-fapi-interaction-id
	hdrXFapiInteractionID := response.GetHeader("x-fapi-interaction-id")

	if hdrXFapiInteractionID != "" {
		o.XFapiInteractionID = hdrXFapiInteractionID
	}

	return nil
}

// NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsTooManyRequests creates a GetDomesticPaymentsDomesticPaymentIDPaymentDetailsTooManyRequests with default headers values
func NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsTooManyRequests() *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsTooManyRequests {
	return &GetDomesticPaymentsDomesticPaymentIDPaymentDetailsTooManyRequests{}
}

/* GetDomesticPaymentsDomesticPaymentIDPaymentDetailsTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type GetDomesticPaymentsDomesticPaymentIDPaymentDetailsTooManyRequests struct {

	/* Number in seconds to wait
	 */
	RetryAfter int64

	/* An RFC4122 UID used as a correlation id.
	 */
	XFapiInteractionID string
}

func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /domestic-payments/{DomesticPaymentId}/payment-details][%d] getDomesticPaymentsDomesticPaymentIdPaymentDetailsTooManyRequests ", 429)
}

func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Retry-After
	hdrRetryAfter := response.GetHeader("Retry-After")

	if hdrRetryAfter != "" {
		valretryAfter, err := swag.ConvertInt64(hdrRetryAfter)
		if err != nil {
			return errors.InvalidType("Retry-After", "header", "int64", hdrRetryAfter)
		}
		o.RetryAfter = valretryAfter
	}

	// hydrates response header x-fapi-interaction-id
	hdrXFapiInteractionID := response.GetHeader("x-fapi-interaction-id")

	if hdrXFapiInteractionID != "" {
		o.XFapiInteractionID = hdrXFapiInteractionID
	}

	return nil
}

// NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsInternalServerError creates a GetDomesticPaymentsDomesticPaymentIDPaymentDetailsInternalServerError with default headers values
func NewGetDomesticPaymentsDomesticPaymentIDPaymentDetailsInternalServerError() *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsInternalServerError {
	return &GetDomesticPaymentsDomesticPaymentIDPaymentDetailsInternalServerError{}
}

/* GetDomesticPaymentsDomesticPaymentIDPaymentDetailsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetDomesticPaymentsDomesticPaymentIDPaymentDetailsInternalServerError struct {

	/* An RFC4122 UID used as a correlation id.
	 */
	XFapiInteractionID string

	/* Header containing a detached JWS signature of the body of the payload.

	 */
	XJwsSignature string

	Payload *models.OBErrorResponse1
}

func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /domestic-payments/{DomesticPaymentId}/payment-details][%d] getDomesticPaymentsDomesticPaymentIdPaymentDetailsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsInternalServerError) GetPayload() *models.OBErrorResponse1 {
	return o.Payload
}

func (o *GetDomesticPaymentsDomesticPaymentIDPaymentDetailsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-fapi-interaction-id
	hdrXFapiInteractionID := response.GetHeader("x-fapi-interaction-id")

	if hdrXFapiInteractionID != "" {
		o.XFapiInteractionID = hdrXFapiInteractionID
	}

	// hydrates response header x-jws-signature
	hdrXJwsSignature := response.GetHeader("x-jws-signature")

	if hdrXJwsSignature != "" {
		o.XJwsSignature = hdrXJwsSignature
	}

	o.Payload = new(models.OBErrorResponse1)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
