// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// OBExternalLocalInstrument1Code User community specific instrument.
// Usage: This element is used to specify a local instrument, local clearing option and/or further qualify the service or service level.
//
// swagger:model OBExternalLocalInstrument1Code
type OBExternalLocalInstrument1Code string

// Validate validates this o b external local instrument1 code
func (m OBExternalLocalInstrument1Code) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this o b external local instrument1 code based on context it is used
func (m OBExternalLocalInstrument1Code) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
