// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// PostCode Identifier consisting of a group of letters and/or numbers that is added to a postal address to assist the sorting of mail.
//
// swagger:model PostCode
type PostCode string

// Validate validates this post code
func (m PostCode) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.MinLength("", "body", string(m), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("", "body", string(m), 16); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this post code based on context it is used
func (m PostCode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
