// Code generated by go-swagger; DO NOT EDIT.

package statements

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetStatementsParams creates a new GetStatementsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetStatementsParams() *GetStatementsParams {
	return &GetStatementsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetStatementsParamsWithTimeout creates a new GetStatementsParams object
// with the ability to set a timeout on a request.
func NewGetStatementsParamsWithTimeout(timeout time.Duration) *GetStatementsParams {
	return &GetStatementsParams{
		timeout: timeout,
	}
}

// NewGetStatementsParamsWithContext creates a new GetStatementsParams object
// with the ability to set a context for a request.
func NewGetStatementsParamsWithContext(ctx context.Context) *GetStatementsParams {
	return &GetStatementsParams{
		Context: ctx,
	}
}

// NewGetStatementsParamsWithHTTPClient creates a new GetStatementsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetStatementsParamsWithHTTPClient(client *http.Client) *GetStatementsParams {
	return &GetStatementsParams{
		HTTPClient: client,
	}
}

/* GetStatementsParams contains all the parameters to send to the API endpoint
   for the get statements operation.

   Typically these are written to a http.Request.
*/
type GetStatementsParams struct {

	/* Authorization.

	   An Authorisation Token as per https://tools.ietf.org/html/rfc6750
	*/
	Authorization string

	/* FromStatementDateTime.

	     The UTC ISO 8601 Date Time to filter statements FROM
	NB Time component is optional - set to 00:00:00 for just Date.
	If the Date Time contains a timezone, the ASPSP must ignore the timezone component.

	     Format: date-time
	*/
	FromStatementDateTime *strfmt.DateTime

	/* ToStatementDateTime.

	     The UTC ISO 8601 Date Time to filter statements TO
	NB Time component is optional - set to 00:00:00 for just Date.
	If the Date Time contains a timezone, the ASPSP must ignore the timezone component.

	     Format: date-time
	*/
	ToStatementDateTime *strfmt.DateTime

	/* XCustomerUserAgent.

	   Indicates the user-agent that the PSU is using.
	*/
	XCustomerUserAgent *string

	/* XFapiAuthDate.

	     The time when the PSU last logged in with the TPP.
	All dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below:
	Sun, 10 Sep 2017 19:43:31 UTC
	*/
	XFapiAuthDate *string

	/* XFapiCustomerIPAddress.

	   The PSU's IP address if the PSU is currently logged in with the TPP.
	*/
	XFapiCustomerIPAddress *string

	/* XFapiInteractionID.

	   An RFC4122 UID used as a correlation id.
	*/
	XFapiInteractionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get statements params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStatementsParams) WithDefaults() *GetStatementsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get statements params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStatementsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get statements params
func (o *GetStatementsParams) WithTimeout(timeout time.Duration) *GetStatementsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get statements params
func (o *GetStatementsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get statements params
func (o *GetStatementsParams) WithContext(ctx context.Context) *GetStatementsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get statements params
func (o *GetStatementsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get statements params
func (o *GetStatementsParams) WithHTTPClient(client *http.Client) *GetStatementsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get statements params
func (o *GetStatementsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get statements params
func (o *GetStatementsParams) WithAuthorization(authorization string) *GetStatementsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get statements params
func (o *GetStatementsParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithFromStatementDateTime adds the fromStatementDateTime to the get statements params
func (o *GetStatementsParams) WithFromStatementDateTime(fromStatementDateTime *strfmt.DateTime) *GetStatementsParams {
	o.SetFromStatementDateTime(fromStatementDateTime)
	return o
}

// SetFromStatementDateTime adds the fromStatementDateTime to the get statements params
func (o *GetStatementsParams) SetFromStatementDateTime(fromStatementDateTime *strfmt.DateTime) {
	o.FromStatementDateTime = fromStatementDateTime
}

// WithToStatementDateTime adds the toStatementDateTime to the get statements params
func (o *GetStatementsParams) WithToStatementDateTime(toStatementDateTime *strfmt.DateTime) *GetStatementsParams {
	o.SetToStatementDateTime(toStatementDateTime)
	return o
}

// SetToStatementDateTime adds the toStatementDateTime to the get statements params
func (o *GetStatementsParams) SetToStatementDateTime(toStatementDateTime *strfmt.DateTime) {
	o.ToStatementDateTime = toStatementDateTime
}

// WithXCustomerUserAgent adds the xCustomerUserAgent to the get statements params
func (o *GetStatementsParams) WithXCustomerUserAgent(xCustomerUserAgent *string) *GetStatementsParams {
	o.SetXCustomerUserAgent(xCustomerUserAgent)
	return o
}

// SetXCustomerUserAgent adds the xCustomerUserAgent to the get statements params
func (o *GetStatementsParams) SetXCustomerUserAgent(xCustomerUserAgent *string) {
	o.XCustomerUserAgent = xCustomerUserAgent
}

// WithXFapiAuthDate adds the xFapiAuthDate to the get statements params
func (o *GetStatementsParams) WithXFapiAuthDate(xFapiAuthDate *string) *GetStatementsParams {
	o.SetXFapiAuthDate(xFapiAuthDate)
	return o
}

// SetXFapiAuthDate adds the xFapiAuthDate to the get statements params
func (o *GetStatementsParams) SetXFapiAuthDate(xFapiAuthDate *string) {
	o.XFapiAuthDate = xFapiAuthDate
}

// WithXFapiCustomerIPAddress adds the xFapiCustomerIPAddress to the get statements params
func (o *GetStatementsParams) WithXFapiCustomerIPAddress(xFapiCustomerIPAddress *string) *GetStatementsParams {
	o.SetXFapiCustomerIPAddress(xFapiCustomerIPAddress)
	return o
}

// SetXFapiCustomerIPAddress adds the xFapiCustomerIpAddress to the get statements params
func (o *GetStatementsParams) SetXFapiCustomerIPAddress(xFapiCustomerIPAddress *string) {
	o.XFapiCustomerIPAddress = xFapiCustomerIPAddress
}

// WithXFapiInteractionID adds the xFapiInteractionID to the get statements params
func (o *GetStatementsParams) WithXFapiInteractionID(xFapiInteractionID *string) *GetStatementsParams {
	o.SetXFapiInteractionID(xFapiInteractionID)
	return o
}

// SetXFapiInteractionID adds the xFapiInteractionId to the get statements params
func (o *GetStatementsParams) SetXFapiInteractionID(xFapiInteractionID *string) {
	o.XFapiInteractionID = xFapiInteractionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetStatementsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.FromStatementDateTime != nil {

		// query param fromStatementDateTime
		var qrFromStatementDateTime strfmt.DateTime

		if o.FromStatementDateTime != nil {
			qrFromStatementDateTime = *o.FromStatementDateTime
		}
		qFromStatementDateTime := qrFromStatementDateTime.String()
		if qFromStatementDateTime != "" {

			if err := r.SetQueryParam("fromStatementDateTime", qFromStatementDateTime); err != nil {
				return err
			}
		}
	}

	if o.ToStatementDateTime != nil {

		// query param toStatementDateTime
		var qrToStatementDateTime strfmt.DateTime

		if o.ToStatementDateTime != nil {
			qrToStatementDateTime = *o.ToStatementDateTime
		}
		qToStatementDateTime := qrToStatementDateTime.String()
		if qToStatementDateTime != "" {

			if err := r.SetQueryParam("toStatementDateTime", qToStatementDateTime); err != nil {
				return err
			}
		}
	}

	if o.XCustomerUserAgent != nil {

		// header param x-customer-user-agent
		if err := r.SetHeaderParam("x-customer-user-agent", *o.XCustomerUserAgent); err != nil {
			return err
		}
	}

	if o.XFapiAuthDate != nil {

		// header param x-fapi-auth-date
		if err := r.SetHeaderParam("x-fapi-auth-date", *o.XFapiAuthDate); err != nil {
			return err
		}
	}

	if o.XFapiCustomerIPAddress != nil {

		// header param x-fapi-customer-ip-address
		if err := r.SetHeaderParam("x-fapi-customer-ip-address", *o.XFapiCustomerIPAddress); err != nil {
			return err
		}
	}

	if o.XFapiInteractionID != nil {

		// header param x-fapi-interaction-id
		if err := r.SetHeaderParam("x-fapi-interaction-id", *o.XFapiInteractionID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
