// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Rate Rate associated with the statement rate type.
//
// swagger:model Rate
type Rate string

// Validate validates this rate
func (m Rate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Pattern("", "body", string(m), `^(-?\d{1,3}){1}(\.\d{1,4}){0,1}$`); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this rate based on context it is used
func (m Rate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
