// Code generated by go-swagger; DO NOT EDIT.

package balances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/cloudentity/openbanking-quickstart/openbanking/accountinformation/models"
)

// GetAccountsAccountIDBalancesReader is a Reader for the GetAccountsAccountIDBalances structure.
type GetAccountsAccountIDBalancesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAccountsAccountIDBalancesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAccountsAccountIDBalancesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAccountsAccountIDBalancesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAccountsAccountIDBalancesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAccountsAccountIDBalancesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewGetAccountsAccountIDBalancesMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 406:
		result := NewGetAccountsAccountIDBalancesNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetAccountsAccountIDBalancesTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAccountsAccountIDBalancesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAccountsAccountIDBalancesOK creates a GetAccountsAccountIDBalancesOK with default headers values
func NewGetAccountsAccountIDBalancesOK() *GetAccountsAccountIDBalancesOK {
	return &GetAccountsAccountIDBalancesOK{}
}

/* GetAccountsAccountIDBalancesOK describes a response with status code 200, with default header values.

Balances Read
*/
type GetAccountsAccountIDBalancesOK struct {

	/* An RFC4122 UID used as a correlation id.
	 */
	XFapiInteractionID string

	Payload *models.OBReadBalance1
}

func (o *GetAccountsAccountIDBalancesOK) Error() string {
	return fmt.Sprintf("[GET /accounts/{AccountId}/balances][%d] getAccountsAccountIdBalancesOK  %+v", 200, o.Payload)
}
func (o *GetAccountsAccountIDBalancesOK) GetPayload() *models.OBReadBalance1 {
	return o.Payload
}

func (o *GetAccountsAccountIDBalancesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-fapi-interaction-id
	hdrXFapiInteractionID := response.GetHeader("x-fapi-interaction-id")

	if hdrXFapiInteractionID != "" {
		o.XFapiInteractionID = hdrXFapiInteractionID
	}

	o.Payload = new(models.OBReadBalance1)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccountsAccountIDBalancesBadRequest creates a GetAccountsAccountIDBalancesBadRequest with default headers values
func NewGetAccountsAccountIDBalancesBadRequest() *GetAccountsAccountIDBalancesBadRequest {
	return &GetAccountsAccountIDBalancesBadRequest{}
}

/* GetAccountsAccountIDBalancesBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetAccountsAccountIDBalancesBadRequest struct {

	/* An RFC4122 UID used as a correlation id.
	 */
	XFapiInteractionID string

	Payload *models.OBErrorResponse1
}

func (o *GetAccountsAccountIDBalancesBadRequest) Error() string {
	return fmt.Sprintf("[GET /accounts/{AccountId}/balances][%d] getAccountsAccountIdBalancesBadRequest  %+v", 400, o.Payload)
}
func (o *GetAccountsAccountIDBalancesBadRequest) GetPayload() *models.OBErrorResponse1 {
	return o.Payload
}

func (o *GetAccountsAccountIDBalancesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-fapi-interaction-id
	hdrXFapiInteractionID := response.GetHeader("x-fapi-interaction-id")

	if hdrXFapiInteractionID != "" {
		o.XFapiInteractionID = hdrXFapiInteractionID
	}

	o.Payload = new(models.OBErrorResponse1)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccountsAccountIDBalancesUnauthorized creates a GetAccountsAccountIDBalancesUnauthorized with default headers values
func NewGetAccountsAccountIDBalancesUnauthorized() *GetAccountsAccountIDBalancesUnauthorized {
	return &GetAccountsAccountIDBalancesUnauthorized{}
}

/* GetAccountsAccountIDBalancesUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAccountsAccountIDBalancesUnauthorized struct {

	/* An RFC4122 UID used as a correlation id.
	 */
	XFapiInteractionID string
}

func (o *GetAccountsAccountIDBalancesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /accounts/{AccountId}/balances][%d] getAccountsAccountIdBalancesUnauthorized ", 401)
}

func (o *GetAccountsAccountIDBalancesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-fapi-interaction-id
	hdrXFapiInteractionID := response.GetHeader("x-fapi-interaction-id")

	if hdrXFapiInteractionID != "" {
		o.XFapiInteractionID = hdrXFapiInteractionID
	}

	return nil
}

// NewGetAccountsAccountIDBalancesForbidden creates a GetAccountsAccountIDBalancesForbidden with default headers values
func NewGetAccountsAccountIDBalancesForbidden() *GetAccountsAccountIDBalancesForbidden {
	return &GetAccountsAccountIDBalancesForbidden{}
}

/* GetAccountsAccountIDBalancesForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAccountsAccountIDBalancesForbidden struct {

	/* An RFC4122 UID used as a correlation id.
	 */
	XFapiInteractionID string

	Payload *models.OBErrorResponse1
}

func (o *GetAccountsAccountIDBalancesForbidden) Error() string {
	return fmt.Sprintf("[GET /accounts/{AccountId}/balances][%d] getAccountsAccountIdBalancesForbidden  %+v", 403, o.Payload)
}
func (o *GetAccountsAccountIDBalancesForbidden) GetPayload() *models.OBErrorResponse1 {
	return o.Payload
}

func (o *GetAccountsAccountIDBalancesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-fapi-interaction-id
	hdrXFapiInteractionID := response.GetHeader("x-fapi-interaction-id")

	if hdrXFapiInteractionID != "" {
		o.XFapiInteractionID = hdrXFapiInteractionID
	}

	o.Payload = new(models.OBErrorResponse1)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccountsAccountIDBalancesMethodNotAllowed creates a GetAccountsAccountIDBalancesMethodNotAllowed with default headers values
func NewGetAccountsAccountIDBalancesMethodNotAllowed() *GetAccountsAccountIDBalancesMethodNotAllowed {
	return &GetAccountsAccountIDBalancesMethodNotAllowed{}
}

/* GetAccountsAccountIDBalancesMethodNotAllowed describes a response with status code 405, with default header values.

Method Not Allowed
*/
type GetAccountsAccountIDBalancesMethodNotAllowed struct {

	/* An RFC4122 UID used as a correlation id.
	 */
	XFapiInteractionID string
}

func (o *GetAccountsAccountIDBalancesMethodNotAllowed) Error() string {
	return fmt.Sprintf("[GET /accounts/{AccountId}/balances][%d] getAccountsAccountIdBalancesMethodNotAllowed ", 405)
}

func (o *GetAccountsAccountIDBalancesMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-fapi-interaction-id
	hdrXFapiInteractionID := response.GetHeader("x-fapi-interaction-id")

	if hdrXFapiInteractionID != "" {
		o.XFapiInteractionID = hdrXFapiInteractionID
	}

	return nil
}

// NewGetAccountsAccountIDBalancesNotAcceptable creates a GetAccountsAccountIDBalancesNotAcceptable with default headers values
func NewGetAccountsAccountIDBalancesNotAcceptable() *GetAccountsAccountIDBalancesNotAcceptable {
	return &GetAccountsAccountIDBalancesNotAcceptable{}
}

/* GetAccountsAccountIDBalancesNotAcceptable describes a response with status code 406, with default header values.

Not Acceptable
*/
type GetAccountsAccountIDBalancesNotAcceptable struct {

	/* An RFC4122 UID used as a correlation id.
	 */
	XFapiInteractionID string
}

func (o *GetAccountsAccountIDBalancesNotAcceptable) Error() string {
	return fmt.Sprintf("[GET /accounts/{AccountId}/balances][%d] getAccountsAccountIdBalancesNotAcceptable ", 406)
}

func (o *GetAccountsAccountIDBalancesNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-fapi-interaction-id
	hdrXFapiInteractionID := response.GetHeader("x-fapi-interaction-id")

	if hdrXFapiInteractionID != "" {
		o.XFapiInteractionID = hdrXFapiInteractionID
	}

	return nil
}

// NewGetAccountsAccountIDBalancesTooManyRequests creates a GetAccountsAccountIDBalancesTooManyRequests with default headers values
func NewGetAccountsAccountIDBalancesTooManyRequests() *GetAccountsAccountIDBalancesTooManyRequests {
	return &GetAccountsAccountIDBalancesTooManyRequests{}
}

/* GetAccountsAccountIDBalancesTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type GetAccountsAccountIDBalancesTooManyRequests struct {

	/* Number in seconds to wait
	 */
	RetryAfter int64

	/* An RFC4122 UID used as a correlation id.
	 */
	XFapiInteractionID string
}

func (o *GetAccountsAccountIDBalancesTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /accounts/{AccountId}/balances][%d] getAccountsAccountIdBalancesTooManyRequests ", 429)
}

func (o *GetAccountsAccountIDBalancesTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Retry-After
	hdrRetryAfter := response.GetHeader("Retry-After")

	if hdrRetryAfter != "" {
		valretryAfter, err := swag.ConvertInt64(hdrRetryAfter)
		if err != nil {
			return errors.InvalidType("Retry-After", "header", "int64", hdrRetryAfter)
		}
		o.RetryAfter = valretryAfter
	}

	// hydrates response header x-fapi-interaction-id
	hdrXFapiInteractionID := response.GetHeader("x-fapi-interaction-id")

	if hdrXFapiInteractionID != "" {
		o.XFapiInteractionID = hdrXFapiInteractionID
	}

	return nil
}

// NewGetAccountsAccountIDBalancesInternalServerError creates a GetAccountsAccountIDBalancesInternalServerError with default headers values
func NewGetAccountsAccountIDBalancesInternalServerError() *GetAccountsAccountIDBalancesInternalServerError {
	return &GetAccountsAccountIDBalancesInternalServerError{}
}

/* GetAccountsAccountIDBalancesInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetAccountsAccountIDBalancesInternalServerError struct {

	/* An RFC4122 UID used as a correlation id.
	 */
	XFapiInteractionID string

	Payload *models.OBErrorResponse1
}

func (o *GetAccountsAccountIDBalancesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /accounts/{AccountId}/balances][%d] getAccountsAccountIdBalancesInternalServerError  %+v", 500, o.Payload)
}
func (o *GetAccountsAccountIDBalancesInternalServerError) GetPayload() *models.OBErrorResponse1 {
	return o.Payload
}

func (o *GetAccountsAccountIDBalancesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-fapi-interaction-id
	hdrXFapiInteractionID := response.GetHeader("x-fapi-interaction-id")

	if hdrXFapiInteractionID != "" {
		o.XFapiInteractionID = hdrXFapiInteractionID
	}

	o.Payload = new(models.OBErrorResponse1)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
